{{- if eq .Values.global.database_location "on-cluster" }}
apiVersion: {{ template "APIVersion" . }}
kind: Deployment
metadata:
  name: deis-database
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-database
  template:
    metadata:
      labels:
        app: deis-database
    spec:
{{- with .Values.global.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      serviceAccount: deis-database
      containers:
        - name: deis-database
          image: {{.Values.org}}/postgres:{{.Values.docker_tag}}
          imagePullPolicy: {{.Values.pull_policy}}
          ports:
            - containerPort: 5432
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          env:
            - name: DATABASE_STORAGE
              value: "{{.Values.global.storage}}"
            - name: PGCTLTIMEOUT
              value: "{{.Values.postgres.timeout}}"
          lifecycle:
            preStop:
              exec:
                command:
                  - su-exec
                  - postgres
                  - do_backup
          readinessProbe:
            exec:
              command:
                - is_running
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: database-creds
              mountPath: /var/run/secrets/deis/database/creds
            - name: objectstore-creds
              mountPath: /var/run/secrets/deis/objectstore/creds
      volumes:
        - name: database-creds
          secret:
            secretName: database-creds
        - name: objectstore-creds
          secret:
            secretName: objectstorage-keyfile
{{- end }}
